# "service" is the name of this project. This will also be added to your AWS resource names.
service: pr8-one-service-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  httpApi: 
    cors: true

functions:
  api:
    handler: dist/index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  # - serverless-plugin-typescript